[extend]
useDefault = true

[allowlist]
description = "Allowlist for sandbox credential placeholders previously in documentation"
commits = [
  "2c2584123d8a75122c962a424846ab5f5f37ff2c",
  "352b4e9b14ce47cebadf61fbc6e3e00a9f9b89d2",
  "be24b7a5715e24ba4e8f3188cefac2b3270a36ca",
]
